name:                project
version:             0.1.0.0
github:              "githubuser/project"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/project#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- hasktorch-tools
- bytestring
- cassava
- vector
- nlp-tools
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# library:
#   source-dirs: src

# executables:
#   project-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - project

executables:
  session3-linear-regression:
    main:               Session3/LinearRegression/LinearRegression.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session3-multiple-x:
    main:               Session3/MultipleX/MultipleX.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session3-graduate:
    main:               Graduate.hs
    source-dirs: Session3/Graduate
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session3-admission:
    main:               AdmissionChances.hs
    source-dirs: Session3/AdmissionChances
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session4-and:
    main:               Session4/AND.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session4-nand:
    main:               Session4/NAND.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session4-xor:
    main:               Session4/XOR.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session5-titanic:
    main:               Titanic.hs
    source-dirs: Session5/Titanic
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  session5-admission:
    main:               AdmissionChances.hs
    source-dirs: 
    - Session5/AdmissionChances
    - Session5/Evaluation
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  # session5-evaluation:
  #   main:               Evaluation.hs
  #   source-dirs: 
  #     - Session5/Evaluation
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N


